import requests

url = "http://localhost:3112/file"

payload={}
files=[
  ('xlsx',('a.xlsx',open('./products.xlsx','rb'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'))
]
headers = {
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjAxOTU3MjA2MjA1IiwidXNlck5hbWUiOiJFYm9uZWFyIFN1cGVyIEFkbWluIiwicm9sZXMiOlt7InJvbGUiOiJTVVBFUl9BRE1JTl9ST0xFIn1dLCJpc1N1cGVyQWRtaW4iOnRydWUsImlzQWRtaW4iOmZhbHNlLCJpc0VtcGxveWVlIjpmYWxzZSwiaXNDdXN0b21lciI6ZmFsc2UsImlzTWVyY2hhbnQiOmZhbHNlLCJpc1VzZXIiOmZhbHNlLCJpc0FmZmlsaWF0b3IiOmZhbHNlLCJpc1RyYW5zcG9ydGVyIjpmYWxzZSwiaXNTaG9wTWFuYWdlciI6ZmFsc2UsInVzZXJJZCI6ImNhNmE5MGUwLTNhNTMtNDNhZS1iMjYyLWEwNjdkMzMxYjljZCIsIlN1cGVyQWRtaW5JZCI6ImNhNmE5MGUwLTNhNTMtNDNhZS1iMjYyLWEwNjdkMzMxYjljZCIsIkFkbWluSWQiOiJjYTZhOTBlMC0zYTUzLTQzYWUtYjI2Mi1hMDY3ZDMzMWI5Y2QiLCJFbXBsb3llZUlkIjpudWxsLCJDdXN0b21lcklkIjpudWxsLCJNZXJjaGFudElkIjpudWxsLCJBZmZpbGlhdG9ySWQiOm51bGwsIlRyYW5zcG9ydGVySWQiOm51bGwsIlNob3BNYW5hZ2VySWQiOm51bGwsImhhc0xpY2Vuc2VBbmROSUQiOmZhbHNlLCJpYXQiOjE2NDQzODQwODksImV4cCI6MTY3NTkyMDA4OX0.S4LeSI3bvi7xQzV1FIVBwkjQz4L1Prf8egCDYsO-hmeFHVpzHljO82US-nZXhiSjc0xpPG_7IbtaqPBGBZOjmg'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
