import requests

url = "http://localhost:3112/file"

payload={}
files=[
  ('xlsx',('a.xlsx',open('/home/pavel/a.xlsx','rb'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'))
]
headers = {
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjAxOTU3MjA2MjA1IiwidXNlck5hbWUiOiJFYm9uZWFyIFN1cGVyIEFkbWluIiwicm9sZXMiOlt7InJvbGUiOiJTVVBFUl9BRE1JTl9ST0xFIn1dLCJpc1N1cGVyQWRtaW4iOnRydWUsImlzQWRtaW4iOmZhbHNlLCJpc0VtcGxveWVlIjpmYWxzZSwiaXNDdXN0b21lciI6ZmFsc2UsImlzTWVyY2hhbnQiOmZhbHNlLCJpc1VzZXIiOmZhbHNlLCJpc0FmZmlsaWF0b3IiOmZhbHNlLCJpc1RyYW5zcG9ydGVyIjpmYWxzZSwiaXNTaG9wTWFuYWdlciI6ZmFsc2UsInVzZXJJZCI6ImNhNmE5MGUwLTNhNTMtNDNhZS1iMjYyLWEwNjdkMzMxYjljZCIsIlN1cGVyQWRtaW5JZCI6ImNhNmE5MGUwLTNhNTMtNDNhZS1iMjYyLWEwNjdkMzMxYjljZCIsIkFkbWluSWQiOiJjYTZhOTBlMC0zYTUzLTQzYWUtYjI2Mi1hMDY3ZDMzMWI5Y2QiLCJFbXBsb3llZUlkIjpudWxsLCJDdXN0b21lcklkIjpudWxsLCJNZXJjaGFudElkIjpudWxsLCJBZmZpbGlhdG9ySWQiOm51bGwsIlRyYW5zcG9ydGVySWQiOm51bGwsIlNob3BNYW5hZ2VySWQiOm51bGwsImhhc0xpY2Vuc2VBbmROSUQiOmZhbHNlLCJpYXQiOjE2NDQxNDExMDAsImV4cCI6MTY3NTY3NzEwMH0.Jycr3tnUQKSc0Ut46Egn0j3W9Yu6iSqiTLlBOOg-EVBHLn7OL4KgcqbIUh2S99BQ1jdJxV0e7Mj-EgzmtTPCGA'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
